#-------------------------------
# Site Settings
title: Keelan Cook
description: The online home for the writings of Keelan Cook.
logo: "/images/logo.png"
logo_dark: "/images/logo.png"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Notes"
      url: "https://notes.keelancook.com"
    - title: "Resources"
      submenu:
      - url: "/projects/"
        title: "Projects"
      - url: "/videos/"
        title: "Videos"
      - url: "/featured/"
        title: "Featured"
      - url: "/tags/"
        title: "Topics"
      - title: "Authors"
        url: "/authors/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Him We Proclaim
  hero_description: The online home for the writings of Keelan Cook. A website for those who love the church and its mission.

hero_authors:
  enable: false
  hero_authors_description: Meet our talented team


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest


#-------------------------------
# Recommended Section Settings
recommended:
  enable: false
  recommended_title: Recommended
  recommended_tag: "Lifestyle"


#-------------------------------
# About Section Settings
about:
  enable: true
  about_title: Hello, I’m Keelan.
  about_subtitle: I serve as the George Liele Director of the Center for Great Commission Studies at Southeastern Baptist Theological Seminary
  about_description: |
    I also serve as instructor of missiology at the seminary. Previously, I served as the Associate Director for the Union Baptist Association in Houston, TX. 

    My areas of focus cover both North American and International missions. I teach and write on church renewal and replanting as well as developing healthy sending culture in churches. I have a passion for mobilizing the church to the nations, and a love for missions history. 

    I lead the Peoples Next Door project, which is an initiative to equip local churches in North America to engage in cross-cultural missions among the least-reached peoples that now live in our communities. I've been a church planter in West Africa with the IMB and facilitated ethnographic research in Washington, DC with NAMB.

  about_image: "/images/keelan-bio.jpeg"
  about_image_alt: Keelan Cook
  about_button_text: More about me
  about_button_link: "/about/"


#-------------------------------
# Authors Section Settings
authors:
  enable: false
  authors_title: Top authors


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Don't miss the next article!
  mailchimp_description: Get notified every time I post a new article, right in your email inbox. Just add your email address to the list below.
  mailchimp_identifier: keelancook.us18.list-manage.com/subscribe/post?u=c5bc34a16760b316bee44bff4&amp;id=dfa9780140&amp;f_id=00a98ae6f0 # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Footer Settings
footer_description: The online home for the writings of Keelan Cook. This site may earn from qualifying purchases as an Amazon Associate.


# Social Links
social:
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com/keelancook"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com/keelancook"}
- {icon: "fas fa-pen-square", name: "Bluesky", link: "https://bsky.app/profile/keelancook.com"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: xyyadopz # Add your form_id
  title: Contact Me
  description: You can always reach out to me by email for inquiries about content on this website, requests for speaking, or other matters related to my work.
  button_text: Send now

# NOTE
# Nomod theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: G-71XX5NEM31 # Add your GA Tracking Id
