name: Generate sitemap

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Required for pushing changes

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for commit history access[3][5]

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://keelancook.com/"  # Replace with your actual URL[1][4]
          # Optional parameters:
          drop-html-extension: true # Removes .html from URLs[1][3]
          # exclude-paths: "private,temp"
          include-pdf: false # Exclude PDFs unless needed[5]
          sitemap-format: xml  # Default, but explicit is good

      - name: Commit and push changes
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "Automated sitemap update"
            git push
          fi
